package com.sh3d.mcp.command;

import com.eteks.sweethome3d.j3d.OBJWriter;
import com.eteks.sweethome3d.model.CatalogPieceOfFurniture;
import com.eteks.sweethome3d.model.HomePieceOfFurniture;
import com.eteks.sweethome3d.tools.OperatingSystem;
import com.eteks.sweethome3d.tools.TemporaryURLContent;
import com.sh3d.mcp.bridge.HomeAccessor;
import com.sh3d.mcp.protocol.Request;
import com.sh3d.mcp.protocol.Response;

import javax.media.j3d.Appearance;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Material;
import javax.media.j3d.Shape3D;
import javax.media.j3d.TransparencyAttributes;
import javax.vecmath.Color3f;
import javax.vecmath.Point3f;

import com.sun.j3d.utils.geometry.GeometryInfo;
import com.sun.j3d.utils.geometry.NormalGenerator;

import static com.sh3d.mcp.command.FormatUtil.round2;

import java.io.File;
import java.net.URL;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Shared utilities for shape generators (extrude and mesh modes).
 * Package-private: used only by ExtrudeShapeGenerator, MeshShapeGenerator,
 * and GenerateShapeHandler.
 */
final class ShapeGeneratorSupport {

    private static final Logger LOG = Logger.getLogger(ShapeGeneratorSupport.class.getName());

    private ShapeGeneratorSupport() {
    }

    /**
     * Adds a Shape3D with auto-generated normals to the BranchGroup.
     */
    static void addShapeToRoot(BranchGroup root, Point3f[] coords, float transparency) {
        GeometryInfo geometryInfo = new GeometryInfo(GeometryInfo.TRIANGLE_ARRAY);
        geometryInfo.setCoordinates(coords);
        new NormalGenerator(0).generateNormals(geometryInfo);

        Appearance appearance = new Appearance();
        appearance.setMaterial(new Material(
                new Color3f(0.2f, 0.2f, 0.2f),
                new Color3f(),
                new Color3f(1.0f, 1.0f, 1.0f),
                new Color3f(),
                0));
        if (transparency > 0) {
            appearance.setTransparencyAttributes(
                    new TransparencyAttributes(TransparencyAttributes.NICEST, transparency));
        }
        root.addChild(new Shape3D(geometryInfo.getIndexedGeometryArray(), appearance));
    }

    /**
     * Exports J3D scene to OBJ ZIP, creates furniture piece, adds to Home.
     */
    static Response exportAndAddToScene(BranchGroup root, String name,
                                         float centerX, float centerY,
                                         float width, float depth, float modelHeight,
                                         float elevation, float transparency,
                                         Integer color, HomeAccessor accessor) {
        try {
            String safeName = name.replaceAll("[^a-zA-Z0-9_-]", "_");
            File tempZipFile = OperatingSystem.createTemporaryFile(safeName, ".zip");
            String objFile = safeName + ".obj";
            OBJWriter.writeNodeInZIPFile(root, tempZipFile, 0, objFile,
                    "Generated by SH3D MCP Plugin");

            URL zipUrl = new URL("jar:" + tempZipFile.toURI().toURL() + "!/" + objFile);
            TemporaryURLContent modelContent = new TemporaryURLContent(zipUrl);

            final String finalName = name;
            final float fw = Math.max(width, 0.1f);
            final float fd = Math.max(depth, 0.1f);
            final float fh = Math.max(modelHeight, 0.1f);

            HomePieceOfFurniture placed = accessor.runOnEDT(() -> {
                CatalogPieceOfFurniture catalogPiece = new CatalogPieceOfFurniture(
                        null, finalName, null, null, modelContent,
                        fw, fd, fh, 0, true, null, null, true, null, null);
                HomePieceOfFurniture piece = new HomePieceOfFurniture(catalogPiece);
                piece.setX(centerX);
                piece.setY(centerY);
                piece.setElevation(elevation);

                if (color != null) {
                    piece.setColor(color);
                }

                accessor.getHome().addPieceOfFurniture(piece);
                return piece;
            });

            Map<String, Object> data = new LinkedHashMap<>();
            data.put("id", placed.getId());
            data.put("name", placed.getName());
            data.put("x", round2(placed.getX()));
            data.put("y", round2(placed.getY()));
            data.put("elevation", round2(placed.getElevation()));
            data.put("width", round2(placed.getWidth()));
            data.put("depth", round2(placed.getDepth()));
            data.put("height", round2(placed.getHeight()));
            return Response.ok(data);

        } catch (Exception e) {
            LOG.log(Level.WARNING, "Failed to generate shape", e);
            return Response.error("Failed to generate shape: " + e.getMessage());
        }
    }

    /**
     * Parses color from request (supports integer and hex string formats).
     */
    static Integer parseColor(Request request) {
        Object colorRaw = request.getParams().get("color");
        if (colorRaw == null) return null;
        if (colorRaw instanceof Number) {
            return ((Number) colorRaw).intValue();
        }
        if (colorRaw instanceof String) {
            String hex = ((String) colorRaw).trim();
            if (hex.startsWith("#")) hex = hex.substring(1);
            if (hex.startsWith("0x") || hex.startsWith("0X")) hex = hex.substring(2);
            return Integer.parseInt(hex, 16);
        }
        return null;
    }

    static float toFloat(Object obj) {
        if (obj instanceof Number) return ((Number) obj).floatValue();
        return Float.parseFloat(obj.toString());
    }

    static int toInt(Object obj) {
        if (obj instanceof Number) return ((Number) obj).intValue();
        return Integer.parseInt(obj.toString());
    }
}
